### PR TITLE
MATSim v12.0

### LINKED ISSUE #124: Current version not compatible with MATSim 12
Hello, I tried to add pt2matsim via pom.xml file and realized it is not working with MATSim 12 because of some changes in MATSim classes/methods (VehicleType for example).
However, just cloning the current repository and using its pom file (or just changing MATSim version to 11 on my project) worked fine.

This is not an issue but a clarification in case someone get into some errors like the following when trying to include the provided snippet into his/her pom.xml file:
Screen Shot 2020-08-21 at 14 02 25

### PR DESCRIPTION
**Pull request by polettif**
Update to MATSim v12.0 from MATSim v11.0, now uses JDK 11.
Closes #124

### CODE REVIEW

**Comment by polettif** [comment]
Could you take a quick glance at this @sebhoerl ? I just changed VehicleCapacity and OptionalTime to get the tests to work, maybe I'm missing something with these classes.

**Comment by sebhoerl** [comment]
I'll try to have a look tonight!

**Comment by sebhoerl** [comment]
I tried to directly compare the generated files before and after... but there are other structural changes in the output so it is hard to compare. From the code it looks good to me, I think it is safe to merge.

**Comment by polettif** [comment]
Alright, thank you!

**Pull request merged**
