### PR TITLE
re-add geotools dependency

### LINKED ISSUE #135: opengis.referencing.NoSuchAuthorityCodeException during Osm2MultimodalNetwork.run
Hello everyone,

I gave a try today with pt2matsim and am getting the error as described in title. 

### Java Version

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

### Matsim Versions 

- matsim: **12.0**
- pt2matsim: **21.1**

### My code 

```java
String inputOsmConfigFile = "original-input-data/config/osm.xml";
OsmConverterConfigGroup osmConfig = OsmConverterConfigGroup.loadConfig(inputOsmConfigFile);
Osm2MultimodalNetwork.run(osmConfig);
````

### Error

```
2021-03-30T01:25:01,937  INFO Counter:74 relation 2693
2021-03-30T01:25:02,440  WARN MGC:174 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2021-03-30T01:25:02,838  INFO FrameworkLogger:-1 dataFileCache open start
2021-03-30T01:25:02,985  WARN MGC:174 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
Exception in thread "main" java.lang.IllegalArgumentException: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:8682" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:177)
	at org.matsim.core.utils.geometry.transformations.GeotoolsTransformation.<init>(GeotoolsTransformation.java:57)
	at org.matsim.core.utils.geometry.transformations.TransformationFactory.getCoordinateTransformation(TransformationFactory.java:80)
	at org.matsim.pt2matsim.osm.OsmMultimodalNetworkConverter.convert(OsmMultimodalNetworkConverter.java:107)
	at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:87)
	at org.matsim.project.RunNetworkAndTransitSchedule.main(RunNetworkAndTransitSchedule.java:33)
Caused by: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:8682" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.geotools.referencing.factory.AbstractAuthorityFactory.noSuchAuthorityCode(AbstractAuthorityFactory.java:874)
	at org.geotools.referencing.factory.epsg.DirectEpsgFactory.createCoordinateReferenceSystem(DirectEpsgFactory.java:2239)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:731)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:731)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.FallbackAuthorityFactory.createCoordinateReferenceSystem(FallbackAuthorityFactory.java:624)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:635)
	at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:176)
	at org.geotools.referencing.CRS.decode(CRS.java:533)
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:175)
```

### Quesion 

Somehow I managed to fix it by adding **gt-referencing** and **gt-epsg-hsql** explicitly
to the **pom.xml** with version **24.2**,  the current one **21.5** that comes with matsim doesn't work for me.
But why? Any help or explaination would be appreciated.

```xml
  <properties>
    <geotools.version>24.2</geotools.version>
 </properties>

 <dependencies>
      <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-referencing</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-epsg-hsql</artifactId>
            <version>${geotools.version}</version>
        </dependency>
 </dependencies>
```

### PR DESCRIPTION
**Pull request by polettif**
Should fix #135

MATSim should depend on a newer geotools version as well (#87, #130) but there's no way to immediately force a version bump.

### CODE REVIEW

**Comment by polettif** [comment]
@sebhoerl How would you handle bumping matsim-libs geotools version? Open a PR or should we keep this here for now?

**Comment by sebhoerl** [comment]
I'll open a PR then it should be in the next release

**Comment by sebhoerl** [comment]
merged :)

**Comment by polettif** [comment]
Nice, thanks!

**Pull request merged**
